name: Publish Package to npmjs

on:
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@23da06e2c4d5804d2082ecf4d79b83a2338fb419 # v0.2
        with:
          envFilePath: ./envvars.for.actions

      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Set env variables
        run: cp apps/webapp/.env.local.example apps/webapp/.env

      - name: Set project example
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          repository: react/react
          path: docs/project-example/react
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 500
          persist-credentials: false

      - name: Publish to npm
        env:
          SMM_STORE_DATA_AT: /home/runner/work/software-metrics-machine/software-metrics-machine/docs/project-example
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm publish --access public --no-git-checks
